name: PR - Validate and Build

permissions: read-all

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - labeled
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: pre-commit
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@f37c44cc085236178ebb8834eb634b0b4b550a40 # v8.23.0
        with:
          skip_checkout: true
      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@fc87bb5b5a97953d987372e74478de634726b3e5 # v3.0.25

  build:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # 4.7.1
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Set preview version
        if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
        run: |
          GITHUB_PR_NUMBER=PR-${{ github.event.pull_request.number }}
          echo 0.0.1-${GITHUB_PR_NUMBER}-${GITHUB_RUN_NUMBER}-SNAPSHOT > VERSION

      - name: Set VERSION env variable
        if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
        run: |
          VERSION=$(cat VERSION)
          echo set VERSION=$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update pom files to the new version
        if: ${{ contains(github.head_ref, 'preview') || contains(github.event.pull_request.labels.*.name, 'preview') }}
        run: mvn -B versions:set -DnewVersion=$VERSION -DprocessAllModules=true -DgenerateBackupPoms=false

      - name: Define Maven Command
        id: define_maven_command
        shell: bash
        run: |
          if [ $DO_PUSH == 'true' ]
          then
            echo "command=deploy" >> $GITHUB_OUTPUT
          else
            echo "command=verify" >> $GITHUB_OUTPUT
          fi
        env:
          DO_PUSH: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}

      - name: Build and Test with Maven (and maybe Deploy)
        shell: bash
        run: mvn ${{ steps.define_maven_command.outputs.command }} -P integration-test ${{ env.MAVEN_CLI_OPTS }}
        env:
          MAVEN_CLI_OPTS: --show-version --no-transfer-progress --settings settings.xml
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Remove the manual merge step - Maven will handle this now

      - name: Generate additional JaCoCo reports if needed
        shell: bash
        run: |
          # Force regenerate aggregate report if it wasn't generated
          if [ ! -f "target/site/jacoco-aggregate/jacoco.xml" ] || [ ! -s "target/site/jacoco-aggregate/jacoco.xml" ]; then
            echo "Generating aggregate report..."
            mvn jacoco:report-aggregate -Djacoco.skip=false -Dquiet=true || echo "Aggregate report generation failed"
          fi

      - name: Set JaCoCo report paths for SonarCloud
        shell: bash
        run: |
          REPORT_PATHS=""

          # First, try the merged report (most comprehensive)
          if [ -f "target/site/jacoco-merged/jacoco.xml" ] && grep -q "<counter" target/site/jacoco-merged/jacoco.xml 2>/dev/null; then
            REPORT_PATHS="target/site/jacoco-merged/jacoco.xml"
            echo "Using merged JaCoCo report"
          # Then try aggregate report
          elif [ -f "target/site/jacoco-aggregate/jacoco.xml" ] && grep -q "<counter" target/site/jacoco-aggregate/jacoco.xml 2>/dev/null; then
            REPORT_PATHS="target/site/jacoco-aggregate/jacoco.xml"
            echo "Using aggregate JaCoCo report"
          # Fall back to collecting all module reports
          else
            echo "No single aggregate report found, collecting module reports..."
            REPORT_PATHS=$(find . -path "*/target/site/jacoco/jacoco.xml" -exec grep -l "<counter" {} \; 2>/dev/null | paste -sd "," - || true)
            if [ -z "$REPORT_PATHS" ]; then
              echo "No JaCoCo reports with coverage data found"
            else
              echo "Found module reports: $REPORT_PATHS"
            fi
          fi

          echo "JACOCO_REPORT_PATHS=$REPORT_PATHS" >> $GITHUB_ENV

      - name: Debug - Check generated files
        shell: bash
        run: |
          set +e  # Don't exit on error for debugging steps
          echo "=== Checking for JaCoCo XML files ==="
          find . -name "jacoco.xml" -type f -exec ls -la {} \; 2>/dev/null | head -20 || echo "No jacoco.xml files found"

          echo "=== Checking for .exec files ==="
          find . -name "*.exec" -type f -exec ls -la {} \; 2>/dev/null | head -20 || echo "No .exec files found"

          echo "=== Checking target directories ==="
          ls -la target/ 2>/dev/null || echo "No target directory"
          ls -la target/site/ 2>/dev/null || echo "No target/site directory"
          ls -la target/site/jacoco-merged/ 2>/dev/null || echo "No target/site/jacoco-merged directory"
          ls -la target/site/jacoco-aggregate/ 2>/dev/null || echo "No target/site/jacoco-aggregate directory"

          echo "=== Checking merged report ==="
          if [ -f "target/site/jacoco-merged/jacoco.xml" ]; then
            echo "Merged report found!"
            echo "File size: $(wc -l target/site/jacoco-merged/jacoco.xml)"
            head -10 target/site/jacoco-merged/jacoco.xml
            echo "Has coverage data: $(grep -c '<counter' target/site/jacoco-merged/jacoco.xml || echo '0')"
          else
            echo "No merged report found"
          fi

          echo "=== Checking aggregate report ==="
          if [ -f "target/site/jacoco-aggregate/jacoco.xml" ]; then
            echo "Aggregate report found!"
            echo "File size: $(wc -l target/site/jacoco-aggregate/jacoco.xml)"
            head -10 target/site/jacoco-aggregate/jacoco.xml
            echo "Has coverage data: $(grep -c '<counter' target/site/jacoco-aggregate/jacoco.xml || echo '0')"
          else
            echo "No aggregate report found"
          fi

          echo "=== Final report paths for SonarCloud ==="
          echo "JACOCO_REPORT_PATHS=$JACOCO_REPORT_PATHS"
          set -e  # Re-enable exit on error

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=activiti \
            -Dsonar.projectKey=Activiti_Activiti \
            -Dsonar.coverage.jacoco.xmlReportPaths=$JACOCO_REPORT_PATHS
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Echo Longest Test Run
        uses: ./.github/actions/echo-longest-run
